baseURL = 'https://frameshift.digital/'
languageCode = 'en-us'
title = 'Frameshift'
theme = 'frameshift-theme'

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 5
  [[menus.main]]
    name = 'About'
    url = '/about/'
    weight = 10
  [[menus.main]]
    name = 'Team'
    url = '/team/'
    weight = 20
  [[menus.main]]
    name = 'News'
    url = '/news/'
    weight = 30
  [[menus.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 40
