baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Catalogue'
    pageRef = '/catalogue'
    weight = 20

  [[menus.main]]
    name = 'News'
    pageRef = '/tags/news'
    weight = 30

  [[menus.main]]
    name = 'Blog'
    pageRef = '/tags/blog'
    weight = 40

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 50

  [[menus.main]]
    name = 'Company'
    pageRef = '/company'
    weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
